name: SCoin
version: 1.0.0
author: solo
api: [3.0.0, 3.1.0, 4.0.0]
main: solo\scoin\SCoin
permissions:
  scoin:
    default: op
    children:
      scoin.command:
        default: op
        children:
          scoin.command.allstatus:
            default: true
          scoin.command.coingive:
            default: op
          scoin.command.coinprice:
            default: true
          scoin.command.coinpurchase:
            default: true
          scoin.command.coinsee:
            default: true
          scoin.command.coinsell:
            default: true
          scoin.command.coinset:
            default: op
          scoin.command.cointake:
            default: op
